# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/PIPNP/PIPNP.runs/synth_1/.Xil/Vivado-17756-DESKTOP-U31JS6B/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/PIPNP/PIPNP.gen/sources_1/ip/clk_wiz_0 C:/Xilinx2/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include c:/PIPNP/PIPNP.gen/sources_1/ip/clk_wiz_0 {
      C:/PIPNP/PIPNP.runs/synth_1/.Xil/Vivado-17756-DESKTOP-U31JS6B/realtime/clk_wiz_0_stub.v
      C:/PIPNP/PIPNP.srcs/sources_1/alu.v
      C:/PIPNP/PIPNP.srcs/sources_1/boy.v
      C:/PIPNP/PIPNP.srcs/sources_1/brom.v
      C:/PIPNP/PIPNP.srcs/sources_1/clk_div.v
      C:/PIPNP/PIPNP.srcs/sources_1/common.v
      C:/PIPNP/PIPNP.srcs/sources_1/control.v
      C:/PIPNP/PIPNP.srcs/sources_1/cpu.v
      C:/PIPNP/PIPNP.srcs/sources_1/dma.v
      C:/PIPNP/PIPNP.srcs/sources_1/ppu.v
      C:/PIPNP/PIPNP.srcs/sources_1/regfile.v
      C:/PIPNP/PIPNP.srcs/sources_1/serial.v
      C:/PIPNP/PIPNP.srcs/sources_1/singleport_ram.v
      C:/PIPNP/PIPNP.srcs/sources_1/singlereg.v
      C:/PIPNP/PIPNP.srcs/sources_1/sound.v
      C:/PIPNP/PIPNP.srcs/sources_1/sound_channel_mix.v
      C:/PIPNP/PIPNP.srcs/sources_1/sound_length_ctr.v
      C:/PIPNP/PIPNP.srcs/sources_1/sound_noise.v
      C:/PIPNP/PIPNP.srcs/sources_1/sound_square.v
      C:/PIPNP/PIPNP.srcs/sources_1/sound_vol_env.v
      C:/PIPNP/PIPNP.srcs/sources_1/sound_wave.v
      C:/PIPNP/PIPNP.srcs/sources_1/timer.v
      C:/PIPNP/PIPNP.srcs/sources_1/vga_font.v
      C:/PIPNP/PIPNP.srcs/sources_1/vga_mixer.v
      C:/PIPNP/PIPNP.srcs/sources_1/vga_timing.v
      C:/PIPNP/PIPNP.srcs/sources_1/new/top.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx2/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/PIPNP/PIPNP.runs/synth_1/.Xil/Vivado-17756-DESKTOP-U31JS6B/realtime/top_synth.xdc
    rt::sdcChecksum
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/PIPNP/PIPNP.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/PIPNP/PIPNP.runs/synth_1/.Xil/Vivado-17756-DESKTOP-U31JS6B/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
